mision_sucre_ripes:
    resource: "@MisionSucreRipesBundle/Resources/config/routing.yml"
    prefix:   /
    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    
app:
    resource: @AppBundle/Controller/
    type:     annotation

usuario:
  path: /usuario
  defaults: { _controller: MisionSucreRipesBundle:Usuario:index }

aldea:
  path: /aldea
  defaults: { _controller: MisionSucreRipesBundle:Aldea:index }
  
ambiente:
  path: /ambiente
  defaults: { _controller: MisionSucreRipesBundle:Ambiente:index }
triunfador:
  path: /triunfador
  defaults: { _controller: MisionSucreRipesBundle:Triunfador:index }
  
docente:
  path: /docente
  defaults: { _controller: MisionSucreRipesBundle:Docente:index }
  
periodo_academico:
  path: admin/periodosacademicos
  defaults: { _controller: MisionSucreRipesBundle:PeriodoAcademico:index }

logout:
    path: /logout
    
login:
    path: /login
    defaults: { _controller: MisionSucreRipesBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: MisionSucreRipesBundle:Security:check }

recuperar_password:
    path: /recuperarpassword
    defaults: { _controller: MisionSucreRipesBundle:Security:recuperarpassword }

home:
    path: /
    defaults: { _controller: MisionSucreRipesBundle:Default:root }

admin:
    path: /admin
    defaults: { _controller: MisionSucreRipesBundle:Default:root }
    
persona:
    path: /persona
    defaults: { _controller: MisionSucreRipesBundle:Persona:index }
    